version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "travel-divider-dev"
s3_bucket = "travel-divider-deployment-dev-eu-west-3"
s3_prefix = "travel-divider"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ExpensesTableName=travel-divider-expenses-dev ReceiptsBucketName=travel-divider-receipts-dev"
tags = "Application=travel-divider Environment=dev"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "travel-divider-dev"
s3_bucket = "travel-divider-deployment-dev-eu-west-3"
s3_prefix = "travel-divider"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ExpensesTableName=travel-divider-expenses-dev ReceiptsBucketName=travel-divider-receipts-dev"
tags = "Application=travel-divider Environment=dev"