AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Travel Divider - Serverless application for tracking and splitting travel expenses

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs18.x
    Environment:
      Variables:
        EXPENSES_TABLE: !Ref ExpensesTable
        RECEIPTS_BUCKET: !Ref ReceiptsBucket

Resources:
  # DynamoDB table for expenses
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: travel-divider-expenses
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: expenseId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # S3 bucket for storing receipt images
  ReceiptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub travel-divider-receipts-${AWS::AccountId}
      # Public access block configuration for enhanced security
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Server-side encryption with Amazon S3-managed keys
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Lifecycle configuration for cost optimization
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReceipts
            Status: Enabled
            ExpirationInDays: 365
          - Id: TransitionToInfrequentAccess
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90
      # CORS configuration for frontend access
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - 'Authorization'
              - 'Content-Type'
              - 'Content-Length'
              - 'x-amz-date'
              - 'x-amz-content-sha256'
              - 'x-amz-security-token'
              - 'X-Requested-With'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - !Sub 'https://${AWS::StackName}.${AWS::Region}.amplifyapp.com'
              - 'http://localhost:3000'
            MaxAge: 3600
            ExposeHeaders:
              - 'ETag'
      # Versioning for data protection and recovery
      VersioningConfiguration:
        Status: Enabled

  # S3 bucket policy to enforce HTTPS
  ReceiptsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReceiptsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub ${ReceiptsBucket.Arn}
              - !Sub ${ReceiptsBucket.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  # IAM role for Lambda functions to access DynamoDB and S3
  TravelDividerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ExpensesTable.Arn
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - !Sub ${ReceiptsBucket.Arn}
                  - !Sub ${ReceiptsBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:PutObjectAcl
                Resource: !Sub ${ReceiptsBucket.Arn}/*
                Condition:
                  StringEquals:
                    's3:x-amz-acl': 'private'

  # Lambda function for creating expenses
  CreateExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/createExpense/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          EXPENSES_TABLE: !Ref ExpensesTable
          RECEIPTS_BUCKET: !Ref ReceiptsBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /expenses
            Method: post

  # Lambda function for getting expenses
  GetExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/getExpenses/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          EXPENSES_TABLE: !Ref ExpensesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /expenses
            Method: get

  # Lambda function for updating expenses
  UpdateExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/updateExpense/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          EXPENSES_TABLE: !Ref ExpensesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /expenses/{expenseId}
            Method: put

  # Lambda function for deleting expenses
  DeleteExpenseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/deleteExpense/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          EXPENSES_TABLE: !Ref ExpensesTable
          RECEIPTS_BUCKET: !Ref ReceiptsBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /expenses/{expenseId}
            Method: delete

  # Lambda function for generating presigned S3 URLs for receipt uploads
  GenerateUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/generateUploadUrl/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          RECEIPTS_BUCKET: !Ref ReceiptsBucket
          ALLOWED_ORIGIN: !Sub 'https://${AWS::StackName}.${AWS::Region}.amplifyapp.com'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /upload-url
            Method: get
        ApiEventOptions:
          Type: Api
          Properties:
            Path: /upload-url
            Method: options

  # Lambda function for generating presigned S3 URLs for downloading receipts
  GetSignedDownloadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/getSignedDownloadUrl/
      Handler: index.handler
      Role: !GetAtt TravelDividerLambdaRole.Arn
      Environment:
        Variables:
          RECEIPTS_BUCKET: !Ref ReceiptsBucket
          ALLOWED_ORIGIN: !Sub 'https://${AWS::StackName}.${AWS::Region}.amplifyapp.com'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /download-url
            Method: get
        ApiEventOptions:
          Type: Api
          Properties:
            Path: /download-url
            Method: options

Outputs:
  ExpensesTable:
    Description: "DynamoDB Table for storing expenses"
    Value: !Ref ExpensesTable

  ReceiptsBucket:
    Description: "S3 Bucket for storing receipt images"
    Value: !Ref ReceiptsBucket
    
  ReceiptsBucketDomainName:
    Description: "S3 Bucket domain name for receipt images"
    Value: !GetAtt ReceiptsBucket.DomainName
    
  ReceiptsBucketUrl:
    Description: "S3 Bucket URL for receipt images"
    Value: !Sub "https://${ReceiptsBucket.DomainName}"

  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    
  UploadUrlEndpoint:
    Description: "Endpoint for generating upload URLs"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload-url"
    
  DownloadUrlEndpoint:
    Description: "Endpoint for generating download URLs"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/download-url"